---
- name: Servidor LAMP
  hosts: all
  tasks:

  - name: Instalando apache no centos
    yum: name={{item}} state=present
    with_items:
      - httpd
    when: ansible_distribution == "CentOS"
    notify: restart httpd

  - name: Instalando pacotes do LAMP
    apt: name={{item}} state=present
    with_items:
      - apache2
    when: ansible_distribution == "Ubuntu"
    notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: restart httpd
      service:
        name: httpd
        state: restarted


