---
- name: instalando o puppet Ubuntu
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: instalando o puppet CentOS
  yum:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Colocando puppet na variavel PATH
  lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:/opt/puppetlabs/bin/"
    create: yes
